"""Add streaks to medicine and action_payload to notification

Revision ID: 24c52db3972f
Revises: 4ffd90a409c6
Create Date: 2026-08-20 12:30:40.811199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24c52db3972f'
down_revision: Union[str, Sequence[str], None] = '4ffd90a409c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicines', sa.Column('current_streak', sa.Integer(), server_default='0', nullable=False))
    op.add_column('medicines', sa.Column('longest_streak', sa.Integer(), server_default='0', nullable=False))
    op.add_column('notifications', sa.Column('action_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'action_payload')
    op.drop_column('medicines', 'longest_streak')
    op.drop_column('medicines', 'current_streak')
    # ### end Alembic commands ###
