"""add status to medication_log

Revision ID: 4ffd90a409c6
Revises: 3a006b57bf77
Create Date: 2026-08-16 19:28:31.329856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ffd90a409c6'
down_revision: Union[str, Sequence[str], None] = '3a006b57bf77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medication_logs', sa.Column('status', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medication_logs', 'status')
    # ### end Alembic commands ###
